### ISSUE TITLE
"Hitta hit"

### ISSUE THREAD

**Issue by pejg12** [dbwebb-se/grillcon#12]
Jag vet inte om jag kan komma än, men jag vet definitivt att jag inte har en aning om hur man hittar dit.

Det står att det går av stapeln vid Studentviken. Är det samma Studentviken som finns på hitta.se ?
http://dela.hitta.se/pl/4000002509

**Comment by mosbth** [comment]
Yep, stämmer bra. Närmaste tågstation är Bergåsa.

**Comment by mosbth** [comment]
Fixade in en karta:
https://grillcon.dbwebb.se/blogg/anmalningar-infor-2016-vt#hitta

**Comment by pejg12** [comment]
Den här informationen försvann 2017...

**Comment by mosbth** [comment]
Lite osäkert om grillen blir just där i år, vi funderar på att förlägga den till BTHs gräsplan istället. Kanske.

Lägger till kartan vi hade för våren 2017.
