### ISSUE TITLE
Anmäl dig här till GrillCon 2016 Höst

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/grillcon#15]
Årets anmälan är nu öppen på GitHub och Facebook.

Om oklarhet finnes, hur man anmälan gör på GitHub, så kika i #2.

**Comment by mosbth** [comment]
Jag kommer. Men min anmälan räknas inte som att vara först. Tvåan vinner (lew fick en serpentin för sin vinst).

**Comment by lewenhagen** [comment]
kommer (vann jag då?)

**Comment by litemerafrukt** [comment]
Jag kommer!

**Comment by forssell** [comment]
Jag kommer!

**Comment by masj2** [comment]
Hej, jag kommer

**Comment by Murquen** [comment]
Jag kommer

**Comment by emilfolino** [comment]
Jag kommer

**Comment by Schanihbg** [comment]
Grilla saker!

**Comment by pansar** [comment]
Jag kanske kommer. Ska kolla schema och grejer. Köp mycket noblesse för säkerhets skull. Skulla jag inte kunna komma loss så går det bra att skicka några lådor med wasa.

**Comment by ghost** [comment]
Jag kommer också!

**Comment by AndreasArne** [comment]
Så klart man kommer!

**Comment by DennisSkoko** [comment]
kommer =)

**Comment by Vandannh** [comment]
Jag kommer!

**Comment by Makaronen** [comment]
Jag kommer
