### ISSUE TITLE
Anmälan till GrillCon 2016 Vår

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/grillcon#2]
# Anmäl dig här till GrillCon 2016 Vår 

Se [webbplatsen](https://grillcon.dbwebb.se) för detaljer om eventet.

Instruktion till hur du anmäler dig.

1) Gör ett inlägg i denna issue och säg "Hej, jag kommer".

2) Någon kommer läsa ditt meddelande och uppfatta det som att du avser komma.

3) Du kan nu betrakta dig som anmäld. Även om du inte kan vara säker på om någon läst just ditt meddelande. Men häng inte upp dig på det.

Låt mig ta det en gång till.

A) Logga in på GitHub.

Låt oss backa ett steg.

pre-A) Skapa ett konto på GitHub.

Vänta lite.

pre-pre-A) GitHub är en tjänst för källkod och Git är ett versionshanteringssystem. Github issues är ett ärendehanteringssystem för källkod och liknande. Med liknande avses här alltså en anälningsprocess till sagda annonserade event.

Hänger du med?

Inte?

Hmmm. [Man kan anmäla sig på Facebook oxå](https://www.facebook.com/events/209303972782488/). Kanske det underlättar?

Ah, vad fint. Anmäl dig på Facebook istället, det går bra det också.  

Åh, du finns inte på Facebook. Men kan [Google+](https://plus.google.com/events/cfsffovrs2gr2c6uggvsneo6f1k) funka för dig då?

Inte det?

Okeeeyyy. Då tar vi det igen.

Klicka på den gröna knappen längst ned till höger, det står "Comment". Det funkar.

**Comment by pansar** [comment]
Är man typ anmäld om man hoppar på detta issue?

**Comment by AndreasArne** [comment]
Blir jag också anmäld om jag gör det?

**Comment by mosbth** [comment]
Alla dessa frågor... klart ni är anmälda.

**Comment by lewenhagen** [comment]
Då är jag också med...

**Comment by kh31d4r** [comment]
Lite oklart hur anmälan går till...

**Comment by masj2** [comment]
http://postimg.org/image/a9n5l39g5/ mobilanpassad grillning... Vad hände med shoppinglistan då? (Tomater)

**Comment by Liljedev** [comment]
~~Kommer kanske, får se hur det löser sig med lust och transport.~~

**Comment by McSlush** [comment]
Kommer!
/Daniel

**Comment by landie** [comment]
olof är en fis

**Comment by bellstrand** [comment]
Jo då, man kommer väll förbi en sväng som vanligt!

**Comment by cruzzan** [comment]
Jag kommer också i alla fall en sväng. Jag är som av en händelse i KNA den helgen.

**Comment by Norberg** [comment]
Hej, jag kommer

**Comment by bobbzorzen** [comment]
Jag kommer delta från ca kl 13:00 och frammåt.

**Comment by pejg12** [comment]
Jag, man och barn kommer ca 14:30. Tar med ett tält för övernattning i skogen också.

**Comment by pt91cs** [comment]
Kommer

**Comment by alfredwester** [comment]
Jag anmäler mig

**Comment by alextalstoi123** [comment]
Hej, jag kommer!

**Comment by philipesmailzade** [comment]
Hej, jag kommer!

**Comment by dambuk** [comment]
Hej, jag kommer!

**Comment by Vandannh** [comment]
Hej, jag kommer!
