### ISSUE TITLE
Omröstning om GrillCon logo

### ISSUE THREAD

**Issue by mosbth** [dbwebb-se/grillcon#3]
Är vi nöjda med den föreslagna logon eller finns det några opponenter och/eller opportunister som vill ställa upp med alternativ logo?

![grillcon_logo_485x500](https://cloud.githubusercontent.com/assets/169550/14491985/73251ede-017c-11e6-9f75-2fb1cbb1aac9.png)

Tävlingen är öppen. SVG är vår teknik.

**Comment by Liljedev** [comment]
:+1:  för logga, :-1: för döskallar

**Comment by mosbth** [comment]
Ugh, den som var sååå snygg och cool. Nåja, finns säkert alternativ. En marshmallow. Eller nåt annat vackert.

**Comment by pansar** [comment]
En brinnande sturköbro?

**Comment by mosbth** [comment]
Inga nya bidrag har inkommit. Vinnaren är "last standing".
