### ISSUE TITLE
Responsiv sida trasig 

### ISSUE THREAD

**Issue by Liljedev** [dbwebb-se/grillcon#8]
< 590px grå border på höger sida som blir större ju smalare bredden blir.

< 466px hoppar meny och bild i header till konstiga positioner:
![](https://i.imgur.com/f4Qg2g8.png)

< 396px överlappar höger och vänster kolumn

**Comment by Liljedev** [comment]
Footern trasar också:
![](https://i.imgur.com/wm3zIXo.png)

Ovan bild är på 375px, aka iphone 6s, som är bredare än de flesta.

**Comment by mosbth** [comment]
Ett steg bättre nu.

Men menyn funkar inte i phone porträtt-läge (TBD). 

Preliminär lösning -Luta mobilen i landskap.

**Comment by mosbth** [comment]
LIte tillfixad så det funkar, den responsiva menyn är iallafall fungerande, men fortfarande småsaker som inte blir som man vill.
