### ISSUE TITLE
Optimera bild som header länkar till.

### ISSUE THREAD

**Issue by Liljedev** [dbwebb-se/grillcon#9]
Tänker specifikt på https://grillcon.dbwebb.se/image/grill-album/johan-snafu-wasa.jpg

Den väger in på 1.7mb vilket känns mycket för vårt mobilanpassade samhälle :)

**Comment by mosbth** [comment]
Hmmm, hur löser jag det smartast? Det blir lite klurigt.

Olika länkar på desktop / mobil eller länka till mindre bild.

Borde nog använda mindre orginalbild som utgångsläge...

Ska se om jag har postprocessing/optimering påslaget för bilder oxå...

**Comment by mosbth** [comment]
Skalade om orginalbilderna till max 1024, optimerade dem och slutligen levererar bilderna via CImage till en lägre kvalitet.

Nu ligger bilderna i ungefär max 100-200 KB. Inte orimligt.
